# Taken from https://github.com/lasote/conan-zlib/blob/release/1.2.8/appveyor.yml
build: false

environment:
    PYTHON: "C:\\Python36-x64\\"
    PYTHON_VERSION: "3.6.3"
    PYTHON_ARCH: "64"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "icu/59.1"
    CONAN_USERNAME: "vitallium"
    CONAN_CHANNEL: "ci"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py